version: '3.3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
    - MYSQL_DATABASE=mysqldb
    - MYSQL_ROOT_PASSWORD=worf
    volumes:
      - /var/lib/mysql

  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      RAILS_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ".:/project"
    depends_on:
      - mysql